spring:
  application:
    name: foxtube

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foxtube
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hades.foxtube.model


jwt:
  secret: $8%^w^k^F4&Gk%m2R1EKS5CsMr!dLxDT6g&B6ox1^$S%y$@JmGeO31643@*$jP1J
  expiration-millisecond: 604800000

azure:
  blob:
    accountName: ${AZURE_BLOB_ACCOUNT}
    containerName: ${AZURE_BLOB_CONTAINER}
    sasToken: ${AZURE_BLOB_SAS_TOKEN}
