name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Zip source code
      run: zip -r source.zip ./*

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: source.zip
